---
title: "p8105_hw5_yc4195.Rmd"
output: github_document
---

```{r settingup, echo=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(p8105.datasets)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r }

```

## Problem 2

```{r}
homicide_df = 
  read_csv("homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    resolve = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )) %>% 
  relocate(city_state) %>% 
  filter(city_state != "Tulsa,AL")
unsolved = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(unsolved = sum(resolve == "unsolved"),
            total_number = n()) 
unsolved
```
The data set consists of `r nrow(homicide_df)` cases, and `r ncol(homicide_df)`  variables that include the time, location, and type of killing, whether an arrest was made, and basic demographic information about each victim.

```{r}
 Baltimore_df =
  unsolved %>% 
  filter(city_state == "Baltimore,MD")

prop.test(
   Baltimore_df %>% pull(unsolved), 
   Baltimore_df %>% pull(total_number)) %>% 
  broom::tidy()

```
The estimated proportion of homicides in Baltimore is 64.6% and its 95% confidence interval is [62.8%, 66.3%].

```{r}
prop_df = unsolved %>% 
  mutate(
    test = map2(.x = unsolved, .y = total_number, ~prop.test(x = .x, n = .y)),
    test = map(test,broom::tidy)
         )  %>% 
  unnest() %>% 
  select(city_state, estimate, conf.low, conf.high) %>%
  arrange(desc(estimate))
plot_df=
  prop_df%>% 
  ggplot(aes(x = reorder(city_state,estimate), y =estimate))+
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.9, hjust = 1))+
  labs(title = "The estimates and CIs for each city",x = "City", y = "Proportions of unsolved homicides")
plot_df
```

## Problem 3

```{r sim}
set.seed(5000)
t_test = function(samp_size, miu = 0, sigma = 5){
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = miu, sd = sigma)
    )
  
  sim_data %>%
  t.test(mu = 0, conf.level = 0.95) %>%
  broom::tidy() %>% 
  select(estimate, p.value)
}
```
